tap "homebrew/cask"
tap "AdoptOpenJDK/openjdk"

cask "adoptopenjdk8"
cask "sublime-text"
cask "firefox"
cask "franz"
cask "intellij-idea-ce"

brew "jump"
brew "maven"
brew "terraform"
brew "mas"

mas "Magnet", id: 441258766
